# Generated by Django 4.2.6 on 2023-10-31 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes_API', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='created_by',
            new_name='creator',
        ),
    ]
